# Generated by Django 2.2.21 on 2021-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product_sap_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sap_unit',
            field=models.CharField(blank=True, help_text='sap profit center', max_length=255, verbose_name='sap unit'),
        ),
    ]
