# Generated by Django 2.2.24 on 2021-11-09 12:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_product_customer_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomergroupdata',
            name='product_cg_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product at that given time.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT'),
        ),
        migrations.AlterField(
            model_name='productcustomergroup',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='This will override product price field.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT'),
        ),
    ]
