# Generated by Django 2.2.21 on 2022-01-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_zero_price_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_by_staff_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed by staff at'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_requested_order',
            field=models.BooleanField(default=False, verbose_name='is requested order'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.TextField(blank=True, default='', verbose_name='payment url'),
        ),
    ]
