# Generated by Django 2.2.27 on 2022-05-04 12:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220125_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.CustomerGroup', verbose_name='Customer group'),
        ),
        migrations.CreateModel(
            name='TimeSlotPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(verbose_name='Time slot begins')),
                ('end', models.TimeField(verbose_name='Time slot ends')),
                ('price', models.DecimalField(decimal_places=2, help_text='This will override product price when applicable.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_prices', to='payments.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Time slot price',
                'verbose_name_plural': 'Time slot prices',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroupTimeSlotPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='This will override product price when applicable.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT')),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_group_time_slot_prices', to='payments.CustomerGroup', verbose_name='Customer group')),
                ('time_slot_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_group_time_slot_prices', to='payments.TimeSlotPrice', verbose_name='Time slot price')),
            ],
            options={
                'verbose_name': 'Customer group time slot price',
                'verbose_name_plural': 'Customer group time slot prices',
                'unique_together': {('customer_group', 'time_slot_price')},
            },
        ),
    ]
