# Generated by Django 2.2.27 on 2022-05-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_product_time_slot_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslotprice',
            options={'ordering': ('product', 'begin'), 'verbose_name': 'Time slot price', 'verbose_name_plural': 'Time slot prices'},
        ),
    ]
