# Generated by Django 2.2.27 on 2022-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_product_time_slot_pricing_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomergroupdata',
            name='price_is_based_on_product_cg',
            field=models.BooleanField(default=False, help_text="Is price based on product customer group price and not product's own default price"),
        ),
    ]
