# Generated by Django 2.2.27 on 2022-05-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_ocgd_price_based_on_cg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslotprice',
            options={'ordering': ('product', 'begin', 'end'), 'verbose_name': 'Time slot price', 'verbose_name_plural': 'Time slot prices'},
        ),
    ]
