# Generated by Django 2.2.27 on 2022-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_fixed_time_slot_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sap_function_area',
            field=models.CharField(blank=True, max_length=16, verbose_name='sap function area'),
        ),
        migrations.AddField(
            model_name='product',
            name='sap_office_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='sap office code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sap_unit',
            field=models.CharField(blank=True, help_text='Equals to sap profit center', max_length=255, verbose_name='sap unit'),
        ),
    ]
