# Generated by Django 2.2.28 on 2022-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_turku_payment_provider_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'online payment'), ('cash', 'cash payment')], default='online', max_length=200, verbose_name='payment method'),
        ),
    ]
