# Generated by Django 4.2.15 on 2024-08-14 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_customer_group_login_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0.00'), (Decimal('10.00'), '10.00'), (Decimal('14.00'), '14.00'), (Decimal('24.00'), '24.00'), (Decimal('25.50'), '25.50')], decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='tax percentage'),
        ),
    ]
