# Generated by Django 2.1.12 on 2019-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190819_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='Birthday'),
        ),
    ]
