# Generated by Django 2.2.14 on 2020-07-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_change_last_name_length'),
        ('users', '0013_squash_auto_spam'),
    ]

    operations = [
    ]
