# Generated by Django 4.2.15 on 2024-08-21 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_extra_prefs_resource_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMethod',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(verbose_name='Name')),
                ('icon', models.FileField(blank=True, null=True, upload_to='loginmethod_icons', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
            options={
                'verbose_name': 'Login method',
                'verbose_name_plural': 'Login methods',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='amr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.loginmethod', verbose_name='Login method'),
        ),
    ]
