services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./media:/var/www/media
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - respa/.env

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db_respa_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - respa/.env

volumes:
  db_respa_data: