# Generated by Django 2.2.5 on 2020-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulkunen', '0003_auto_20190819_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolsystem',
            name='driver',
            field=models.CharField(choices=[('sipass', 'Siemens SiPass'), ('abloy', 'Abloy')], max_length=30),
        ),
    ]
