# Generated by Django 3.2.18 on 2023-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulkunen', '0004_auto_20200316_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolgrant',
            name='driver_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolresource',
            name='driver_config',
            field=models.JSONField(blank=True, help_text='Driver-specific configuration', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolresource',
            name='driver_data',
            field=models.JSONField(editable=False, help_text='Internal driver data', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsystem',
            name='driver_config',
            field=models.JSONField(blank=True, help_text='Driver-specific configuration', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsystem',
            name='driver_data',
            field=models.JSONField(editable=False, help_text='Internal driver data', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontroluser',
            name='driver_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
