# Generated by Django 2.1.12 on 2019-10-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkusers', '0001_add_ad_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turkuadgroup',
            options={'verbose_name': 'AD Group'},
        ),
    ]
