# Generated by Django 2.2.26 on 2022-02-15 10:51

from django.db import migrations, models
import respa_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0129_add_is_external_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledFieldsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('disabled_fields', respa_admin.models.ChoiceArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None, verbose_name='disabled fields')),
                ('resources', models.ManyToManyField(blank=True, help_text='If selected, fields will be disabled for selected resources only, takes priority over unit.', limit_choices_to={'is_external': True}, related_name='disabled_fields_set', to='resources.Resource', verbose_name='resources')),
                ('units', models.ManyToManyField(blank=True, help_text='If selected, fields will be disabled for all resources that belong to the selected units.', limit_choices_to={'resources__is_external': True}, related_name='disabled_fields_set', to='resources.Unit', verbose_name='units')),
            ],
            options={
                'verbose_name': 'disabled field set',
                'verbose_name_plural': 'disabled fields set',
            },
        ),
    ]
