# Generated by Django 3.2.18 on 2023-02-23 05:41

from django.db import migrations, models
import respa_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_admin', '0001_add_disabled_fields_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledfieldsset',
            name='disabled_fields',
            field=respa_admin.models.ChoiceArrayField(base_field=models.CharField(choices=[], max_length=256), blank=True, default=list, null=True, size=None, verbose_name='disabled fields'),
        ),
    ]
