# Generated by Django 2.2.16 on 2020-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_o365', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='exchange_reservation_sync_memento',
            field=models.TextField(null=True, verbose_name='Last known state of Exchange reservations'),
        ),
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='respa_reservation_sync_memento',
            field=models.TextField(null=True, verbose_name='Last known state of Respa reservations'),
        ),
    ]
