# Generated by Django 2.2.16 on 2020-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_o365', '0002_fields_for_sync_source_mementos'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='exchange_subscription_id',
            field=models.TextField(null=True, verbose_name='Id of the registered notification listener'),
        ),
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='exchange_subscription_secret',
            field=models.TextField(null=True, verbose_name='Secret used by the notifier'),
        ),
    ]
