# Generated by Django 2.2.16 on 2021-02-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0124_auto_20210225_1123'),
        ('respa_o365', '0003_fields_for_outlook_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='exchange_availability_sync_memento',
            field=models.TextField(null=True, verbose_name='Last known state of Exchange availability'),
        ),
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='respa_availability_sync_memento',
            field=models.TextField(null=True, verbose_name='Last known state of Respa availability'),
        ),
        migrations.CreateModel(
            name='OutlookCalendarAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.TextField(unique=True, verbose_name='Exchange ID')),
                ('exchange_change_key', models.TextField(verbose_name='Exchange Change Key')),
                ('respa_change_key', models.TextField(verbose_name='Respa Change Key')),
                ('calendar_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respa_o365.OutlookCalendarLink', verbose_name='Calendar Link')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Period', verbose_name='Period')),
            ],
        ),
    ]
