# Generated by Django 2.2.16 on 2021-03-31 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_o365', '0004_availability_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookSyncQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('calendar_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respa_o365.OutlookCalendarLink', verbose_name='Calendar Link')),
            ],
        ),
    ]
