# Generated by Django 2.2.16 on 2021-06-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_o365', '0005_outlooksyncqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookcalendarlink',
            name='microsoft_user_id',
            field=models.TextField(default=1, unique=True, verbose_name='ID of user from Microsoft API'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outlookcalendarlink',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', unique=True, verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='outlookcalendarlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='User'),
        ),
    ]
