# Generated by Django 2.2.21 on 2021-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_create_accessibility_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequirement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='servicerequirement',
            name='is_indoor_requirement',
            field=models.BooleanField(default=False),
        ),
    ]
