# Generated by Django 3.2.18 on 2023-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_change_requirement_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentrance',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
