# Generated by Django 2.2.5 on 2020-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_outlook', '0002_auto_20200205_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='respaoutlookreservation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified'),
        ),
    ]
