# Generated by Django 2.2.28 on 2022-10-12 13:59

from django.db import migrations, models
import qualitytool.models
import respa_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0138_add_slot_size_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityToolFormLanguageOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', respa_admin.models.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], max_length=255), default=qualitytool.models.get_form_defaults, size=None, verbose_name='Form options')),
            ],
            options={
                'verbose_name': 'Qualitytool form configuration',
            },
        ),
        migrations.CreateModel(
            name='ResourceQualityTool',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Nimi')),
                ('name_fi', models.CharField(max_length=255, null=True, verbose_name='Nimi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nimi')),
                ('name_sv', models.CharField(max_length=255, null=True, verbose_name='Nimi')),
                ('target_id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Target ID')),
                ('resources', models.ManyToManyField(to='resources.Resource', verbose_name='Resurssit')),
            ],
            options={
                'verbose_name': 'resource quality tool',
                'verbose_name_plural': 'resource quality tools',
            },
        ),
    ]
