# Generated by Django 2.2.28 on 2022-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitytool', '0001_create_qualitytool_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitytoolformlanguageoptions',
            options={'verbose_name': 'Quality tool form configuration'},
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='resources',
            field=models.ManyToManyField(related_name='qualitytool', to='resources.Resource', verbose_name='Resources'),
        ),
    ]
