# Generated by Django 2.2.28 on 2023-02-14 11:52

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qualitytool', '0002_qualitytool_field_alters'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcequalitytool',
            name='emails',
            field=django_jsonform.models.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Email'), blank=True, null=True, size=None),
        ),
    ]
