# Generated by Django 4.2.13 on 2024-08-14 06:52

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0156_overnight_reservation_fields'),
        ('qualitytool', '0003_add_qualitytool_emails_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcequalitytool',
            options={'verbose_name': 'resurssi laatutyökalu', 'verbose_name_plural': 'resurssi laatutyökalut'},
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='emails',
            field=django_jsonform.models.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Sähköpostiosoite'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='resourcequalitytool',
            name='resources',
            field=models.ManyToManyField(related_name='qualitytool', to='resources.resource', verbose_name='Resurssit'),
        ),
    ]
