# Generated by Django 2.2.11 on 2020-05-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20200323_1026'),
        ('notifications', '0012_auto_20200326_1157'),
    ]

    operations = [
    ]
