# Generated by Django 2.2.11 on 2020-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20200917_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='template_group',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_default_template',
            field=models.BooleanField(default=False, verbose_name='Set this template as a default template.'),
        ),
    ]
