# Generated by Django 2.2.11 on 2020-09-22 07:03

from django.db import migrations


def set_existing_as_default(apps, schema_editor):
    Notifications = apps.get_model('notifications','NotificationTemplate')
    for notification in Notifications.objects.all():
        notification.is_default_template = True
        notification.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20200922_0957'),
    ]

    operations = [
        migrations.RunPython(set_existing_as_default),
    ]
