# Generated by Django 2.2.11 on 2020-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20200922_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplategroup',
            options={'ordering': ('name',), 'verbose_name': 'Notification template group', 'verbose_name_plural': 'Notification template groups'},
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_default_template',
            field=models.BooleanField(default=False, help_text='Use this template as a default template for this type.', verbose_name='Set this template as a default template.'),
        ),
        migrations.AlterField(
            model_name='notificationtemplategroup',
            name='templates',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_default_template': False}, related_name='groups', to='notifications.NotificationTemplate', verbose_name='Notification templates'),
        ),
    ]
