# Generated by Django 2.2.21 on 2022-01-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20200922_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested official'), ('reservation_requested_official_by_official', 'Reservation requested by official'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_cancelled_official', 'Reservation cancelled official'), ('reservation_cancelled_by_official', 'Reservation cancelled by official'), ('reservation_created', 'Reservation created'), ('reservation_created_official', 'Reservation created official'), ('reservation_created_by_official', 'Reservation created by official'), ('reservation_modified', 'Reservation modified'), ('reservation_modified_official', 'Reservation modified official'), ('reservation_modified_by_official', 'Reservation modified by official'), ('reservation_created_with_access_code', 'Reservation created with access code'), ('reservation_created_with_access_code_official', 'Reservation created with access code official'), ('reservation_created_with_access_code_by_official', 'Reservation created with access code by official'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation denied'), ('reservation_access_code_created', 'Access code was created for a reservation'), ('reservation_waiting_for_payment', 'Reservation waiting for payment'), ('catering_order_created', 'Catering order created'), ('catering_order_modified', 'Catering order modified'), ('catering_order_deleted', 'Catering order deleted'), ('reservation_comment_created', 'Reservation comment created'), ('catering_order_comment_created', 'Catering order comment created'), ('reservation_bulk_created', 'Reservation bulk created')], db_index=True, max_length=100, verbose_name='Type'),
        ),
    ]
