# Generated by Django 2.1.9 on 2019-09-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0080_auto_20190819_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('modified', 'modified'), ('denied', 'denied'), ('requested', 'requested')], default='created', max_length=16, verbose_name='State'),
        ),
    ]
