# Generated by Django 2.1.9 on 2019-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0081_auto_20190903_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='require_assistance',
            field=models.BooleanField(default=False, verbose_name='Require assistance'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
    ]
