# Generated by Django 2.1.9 on 2019-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0081_auto_20190903_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='reservation_extra_questions',
            new_name='reservation_extra_questions_en',
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions'),
        ),
    ]
