# Generated by Django 2.1.11 on 2019-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0082_auto_20190906_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='preferred_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], default='fi', max_length=8, null=True, verbose_name='Preferred Language'),
        ),
    ]
