# Generated by Django 2.1.9 on 2019-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0082_auto_20190904_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [En]'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [Fi]'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [Sv]'),
        ),
    ]
