# Generated by Django 2.1.9 on 2019-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0083_auto_20190904_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_extra_questions',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [En]'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [Fi]'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [Sv]'),
        ),
    ]
