# Generated by Django 2.1.9 on 2019-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0084_auto_20190904_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [en]'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [fi]'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [sv]'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_en',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [en]'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_fi',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [fi]'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_extra_questions_sv',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions [sv]'),
        ),
    ]
