# Generated by Django 2.1.12 on 2019-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0084_auto_20190911_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='age_restriction',
            field=models.PositiveIntegerField(default=18, verbose_name='Age restriction'),
        ),
    ]
