# Generated by Django 2.1.12 on 2019-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0085_resource_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('modified while requesting', 'modified while requesting'), ('modified after confirm', 'modified after confirm'), ('denied', 'denied'), ('requested', 'requested')], default='created', max_length=16, verbose_name='State'),
        ),
    ]
