# Generated by Django 2.1.9 on 2019-09-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0082_auto_20190906_1415'),
        ('resources', '0085_auto_20190904_1234'),
    ]

    operations = [
    ]
