# Generated by Django 2.1.12 on 2019-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0088_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='age_restriction',
        ),
        migrations.AddField(
            model_name='resource',
            name='max_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Age restriction (max)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Age restriction (min)'),
        ),
    ]
