# Generated by Django 2.2.11 on 2020-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0089_auto_20200317_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
    ]
