# Generated by Django 2.1.12 on 2019-09-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0089_auto_20190912_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='max_age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age restriction (max)'),
        ),
    ]
