# Generated by Django 2.2.11 on 2020-03-26 12:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0090_auto_20200326_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='resources.CleanResourceID', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
