# Generated by Django 2.1.12 on 2019-09-12 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0090_auto_20190912_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cooldown',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Reservation cooldown'),
        ),
    ]
