# Generated by Django 2.1.12 on 2019-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0091_resource_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('requested', 'requested'), ('cooldown', 'cooldown')], default='created', max_length=16, verbose_name='State'),
        ),
    ]
