# Generated by Django 2.1.12 on 2019-09-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0093_auto_20190913_0810'),
        ('resources', '0081_reservation_type'),
    ]

    operations = [
    ]
