# Generated by Django 2.1.12 on 2019-09-16 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0096_auto_20190913_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cooldown',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Reservation cooldown'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slot_size',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), null=True, verbose_name='Slot size for reservation time'),
        ),
    ]
