# Generated by Django 2.1.12 on 2019-09-16 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0097_auto_20190916_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cooldown',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Reservation cooldown'),
        ),
    ]
