# Generated by Django 2.1.12 on 2019-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0099_auto_20190917_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Age restriction (max)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Age restriction (min)'),
        ),
    ]
