# Generated by Django 2.1.12 on 2019-09-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0101_auto_20190917_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='map_service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
