# Generated by Django 2.1.12 on 2019-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0102_unit_map_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='map_service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Map service ID'),
        ),
    ]
