# Generated by Django 2.1.12 on 2019-09-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0103_auto_20190919_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_participants',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Number of participants'),
        ),
    ]
