# Generated by Django 2.2.5 on 2019-10-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0082_unit_data_sources'),
        ('resources', '0104_auto_20190924_0915'),
    ]

    operations = [
    ]
