# Generated by Django 2.1.12 on 2019-10-30 08:30

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0105_merge_20191028_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_staff_emails',
            field=multi_email_field.fields.MultiEmailField(blank=True, null=True),
        ),
    ]
