# Generated by Django 2.1.12 on 2019-10-30 09:54

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0106_resource_resource_staff_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_staff_emails',
            field=multi_email_field.fields.MultiEmailField(blank=True, null=True, verbose_name='E-mail addresses for client correspondence'),
        ),
    ]
