# Generated by Django 2.1.12 on 2019-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0107_auto_20191030_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='require_workstation',
            field=models.BooleanField(default=False, verbose_name='Require workstation'),
        ),
    ]
