# Generated by Django 2.2.5 on 2020-01-24 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0109_reservationbulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='sms_reminder',
            field=models.BooleanField(default=False, verbose_name='SMS Reminder'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sms_reminder_delay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)], verbose_name='SMS Delay (hours)'),
        ),
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(verbose_name='Reminder Date')),
                ('notification_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Notification type')),
                ('action_by_official', models.BooleanField(blank=True, null=True, verbose_name='Action by official')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='resources.Reservation', verbose_name='Reservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReservationReminders', to='resources.ReservationReminder', verbose_name='Reservation Reminder'),
        ),
    ]
