# Generated by Django 2.2.5 on 2020-01-27 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0110_auto_20200124_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='sms_reminder',
            field=models.BooleanField(default=False, verbose_name='Send SMS Reminder'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sms_reminder_delay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8766)], verbose_name='How many hours before reservation the reminder is sent'),
        ),
    ]
