# Generated by Django 2.2.10 on 2020-02-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0111_auto_20200127_0856'),
        ('resources', '0086_more_additions_to_permissions'),
    ]

    operations = [
    ]
