# Generated by Django 2.2.11 on 2020-04-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0088_auto_20200319_1053'),
        ('resources', '0114_auto_20200317_0836'),
    ]

    operations = [
    ]
