# Generated by Django 2.2.11 on 2020-05-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0091_auto_20200326_1439'),
        ('resources', '0115_merge_20200406_1419'),
    ]

    operations = [
    ]
