# Generated by Django 2.2.14 on 2020-07-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0118_auto_20200622_1251'),
        ('resources', '0091_add_two_permissions'),
    ]

    operations = [
    ]
