# Generated by Django 2.2.14 on 2020-08-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0120_auto_20200724_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityvalue',
            options={'ordering': ('order',), 'verbose_name': 'saavutettavuusarvo', 'verbose_name_plural': 'accessibility values'},
        ),
        migrations.AlterModelOptions(
            name='accessibilityviewpoint',
            options={'ordering': ('order_text',), 'verbose_name': 'saavutettavuusnäkökulma', 'verbose_name_plural': 'accessibility viewpoints'},
        ),
        migrations.AlterModelOptions(
            name='resourceaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'resurssin saavutettavuuden yhteenveto', 'verbose_name_plural': 'resurssin saavutettavuuden yhteenvedot'},
        ),
        migrations.AlterModelOptions(
            name='unitaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'toimipisteen saavutettavuuden yhteenveto', 'verbose_name_plural': 'toimipisteen saavutettavuuden yhteenvedot'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_arrived',
            field=models.BooleanField(default=False, verbose_name='Has arrived'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='value',
            field=models.CharField(max_length=128, unique=True, verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='order_text',
            field=models.CharField(default='0', max_length=200, verbose_name='Tilaus'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Resource', verbose_name='Resurssi'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Unit', verbose_name='Resurssi'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
    ]
