# Generated by Django 2.2.11 on 2020-09-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20200917_1300'),
        ('resources', '0121_add_has_arrived_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityvalue',
            options={'ordering': ('order',), 'verbose_name': 'accessibility value', 'verbose_name_plural': 'accessibility values'},
        ),
        migrations.AlterModelOptions(
            name='accessibilityviewpoint',
            options={'ordering': ('order_text',), 'verbose_name': 'accessibility viewpoint', 'verbose_name_plural': 'accessibility viewpoints'},
        ),
        migrations.AlterModelOptions(
            name='resourceaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'resource accessibility summary', 'verbose_name_plural': 'resource accessibility summaries'},
        ),
        migrations.AlterModelOptions(
            name='unitaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'unit accessibility summary', 'verbose_name_plural': 'unit accessibility summaries'},
        ),
        migrations.AddField(
            model_name='unit',
            name='notification_template_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.NotificationTemplateGroup', verbose_name='Notification Template Group'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordering priority'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='value',
            field=models.CharField(max_length=128, unique=True, verbose_name='Accessibility summary value'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resource ordering priority'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Accessibility summary value'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resource Accessibility'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resource ordering priority'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Accessibility summary value'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resource Accessibility'),
        ),
    ]
