# Generated by Django 2.2.16 on 2021-02-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0123_auto_20201103_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanresourceid',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_cleanresourceid_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
