# Generated by Django 2.2.16 on 2021-01-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0124_auto_20210225_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timmi_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Timmi ID'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timmi_receipt',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Timmi receipt'),
        ),
        migrations.AddField(
            model_name='resource',
            name='timmi_resource',
            field=models.BooleanField(blank=True, default=False, help_text='Is this resource part of Timmi integration?', verbose_name='Is Timmi resource?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='timmi_room_id',
            field=models.PositiveIntegerField(blank=True, help_text='This field will attempt to auto-fill if room id isn\'t provided.', null=True, verbose_name='Timmi ID'),
        ),
        migrations.AddField(
            model_name='unit',
            name='timmi_profile_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Timmi profile id')
        ),
        migrations.AlterField(
            model_name='cleanresourceid',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_cleanresourceid_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
