# Generated by Django 2.2.18 on 2021-03-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0124_timmi_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimmiPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_payload', models.TextField(blank=True, null=True, verbose_name='Timmi payload')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timmi_payload_orders', to='payments.Order', verbose_name='Order')),
            ],
        ),
    ]
