# Generated by Django 2.2.21 on 2021-06-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0125_add_timmi_payload_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='disallow_overlapping_reservations_per_user',
            field=models.BooleanField(default=False, verbose_name='Disallow overlapping reservations in this unit per user.'),
        ),
    ]
