# Generated by Django 2.2.21 on 2021-06-09 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0125_add_timmi_payload_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='purpose_images', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
