# Generated by Django 2.2.21 on 2021-06-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0126_purpose_image'),
        ('resources', '0126_add_field_disallow_overlapping_reservations_per_user'),
    ]

    operations = [
    ]
