# Generated by Django 2.2.21 on 2021-06-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0127_merge_hotfix_conflicts'),
        ('resources', '0127_create_resource_tag'),
    ]

    operations = [
    ]
