# Generated by Django 2.2.26 on 2022-01-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0128_merge_hotfix_resource_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_external',
            field=models.BooleanField(blank=True, default=False, verbose_name='Externally managed resource'),
        ),
    ]
