# Generated by Django 2.2.27 on 2022-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0130_add_missing_accessibility_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='payment_requested_waiting_time',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Amount of hours before confirmed preliminary reservations with payments expire. Value 0 means this setting is not in use.', verbose_name='Preliminary reservation payment waiting time'),
        ),
        migrations.AddField(
            model_name='unit',
            name='payment_requested_waiting_time',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Amount of hours before confirmed preliminary reservations with payments expire. Value 0 means this setting is not in use.', verbose_name='Preliminary reservation payment waiting time'),
        ),
    ]
