# Generated by Django 2.2.27 on 2022-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0131_payment_requested_waiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceimage',
            name='stamp',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
