# Generated by Django 2.2.27 on 2022-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0133_add_maintenance_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_feedback_url',
            field=models.URLField(blank=True, help_text='A link to an external feedback system', verbose_name='Reservation feedback URL'),
        ),
    ]
