# Generated by Django 2.2.28 on 2022-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0134_reservation_feedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
