# Generated by Django 2.2.28 on 2022-06-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0135_drop_purpose_name_length_to_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='takes_place_virtually',
            field=models.BooleanField(default=False, verbose_name='Takes place virtually'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='virtual_address',
            field=models.TextField(blank=True, verbose_name='Virtual address'),
        ),
    ]
