# Generated by Django 2.2.28 on 2022-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0136_virtual_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cash_payments_allowed',
            field=models.BooleanField(default=False, help_text='Allows cash payment option for paid reservations. Can only be set when resource needs manual confirmation.', verbose_name='Cash payments allowed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('requested', 'requested'), ('waiting_for_payment', 'waiting for payment'), ('ready_for_payment', 'ready for payment'), ('waiting_for_cash_payment', 'waiting for cash payment')], default='created', max_length=32, verbose_name='State'),
        ),
    ]
