# Generated by Django 2.2.28 on 2022-09-28 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0137_cash_payment_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slot_size',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), help_text='Note! If there are any products with per_period pricing that are attached to this resource, make sure that slot_size value is the same size as the products price_period value.', null=True, verbose_name='Slot size for reservation time'),
        ),
    ]
