# Generated by Django 2.2.28 on 2022-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0139_add_api_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='soft_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Soft deleted resource'),
        ),
    ]