# Generated by Django 2.2.28 on 2023-02-10 11:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0141_add_soft_delete_api_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUniversalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data')),
                ('label', models.CharField(max_length=100, verbose_name='Heading')),
                ('label_fi', models.CharField(max_length=100, null=True, verbose_name='Heading')),
                ('label_en', models.CharField(max_length=100, null=True, verbose_name='Heading')),
                ('label_sv', models.CharField(max_length=100, null=True, verbose_name='Heading')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fi', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_sv', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceuniversalfield_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'resource universal form field',
                'verbose_name_plural': 'resource universal form fields',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='universal_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='UniversalFormFieldType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200, verbose_name='Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universalformfieldtype_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universalformfieldtype_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'universal form field type',
                'verbose_name_plural': 'universal form field types',
            },
        ),
        migrations.CreateModel(
            name='ResourceUniversalFormOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('text_fi', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('text_sv', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='Sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceuniversalformoption_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceuniversalformoption_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_universal_form_option', to='resources.Resource')),
                ('resource_universal_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceUniversalField', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'resource universal form option',
                'verbose_name_plural': 'resource universal form options',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='resourceuniversalfield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_universal_field', to='resources.UniversalFormFieldType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='resourceuniversalfield',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceuniversalfield_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='resourceuniversalfield',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_universal_field', to='resources.Resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='universal_field',
            field=models.ManyToManyField(through='resources.ResourceUniversalField', to='resources.UniversalFormFieldType', verbose_name='Universal fields'),
        ),
    ]
