# Generated by Django 3.2.18 on 2023-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0143_django_3_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservable_by_all_staff',
            field=models.BooleanField(default=False, help_text='All staff users can create reservations on behalf of customers', verbose_name='Resource is reservable by all staff users'),
        ),
    ]
