# Generated by Django 3.2.18 on 2023-05-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0144_resource_reservable_by_all_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='disallow_overlapping_reservations_per_user',
            field=models.BooleanField(default=False, help_text='This rule does not apply for unauthenticated users', verbose_name='Disallow overlapping reservations in this unit only for the same user.'),
        ),
    ]
