# Generated by Django 3.2.18 on 2023-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0145_unit_per_user_overlap_for_anon_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='private_event',
            field=models.BooleanField(default=False, verbose_name='Private event'),
        ),
    ]
