# Generated by Django 3.2.20 on 2023-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0146_add_private_event_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserver_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Reserver ID (business)'),
        ),
    ]
