# Generated by Django 3.2.19 on 2023-09-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0148_add_maintenance_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintenancemode',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='maintenancemode',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='MaintenanceMessage',
        ),
        migrations.DeleteModel(
            name='MaintenanceMode',
        ),
    ]
