# Generated by Django 3.2.23 on 2024-01-29 05:51

from django.db import migrations, models
import django.db.models.deletion
import resources.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0151_remove_unused_reminder_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='public',
            new_name='_public',
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=resources.fields.TranslatedCharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_en',
            field=resources.fields.TranslatedCharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_fi',
            field=resources.fields.TranslatedCharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_sv',
            field=resources.fields.TranslatedCharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_additional_information',
            field=resources.fields.TranslatedTextField(blank=True, verbose_name='Reservation additional information'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_additional_information_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation additional information'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_additional_information_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation additional information'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_additional_information_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation additional information'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_confirmed_notification_extra',
            field=resources.fields.TranslatedTextField(blank=True, verbose_name='Extra content to "reservation confirmed" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_confirmed_notification_extra_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation confirmed" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_confirmed_notification_extra_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation confirmed" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_confirmed_notification_extra_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation confirmed" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_requested_notification_extra',
            field=resources.fields.TranslatedTextField(blank=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_requested_notification_extra_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_requested_notification_extra_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_requested_notification_extra_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='responsible_contact_info',
            field=resources.fields.TranslatedTextField(blank=True, verbose_name='Responsible contact info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='responsible_contact_info_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Responsible contact info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='responsible_contact_info_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Responsible contact info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='responsible_contact_info_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Responsible contact info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='specific_terms',
            field=resources.fields.TranslatedTextField(blank=True, verbose_name='Specific terms'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='specific_terms_en',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='specific_terms_fi',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='specific_terms_sv',
            field=resources.fields.TranslatedTextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.CreateModel(
            name='ResourcePublishDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(blank=True, help_text='Resource will be public after this date', null=True, verbose_name='Begin time')),
                ('end', models.DateTimeField(blank=True, help_text='Resource will be hidden after this date', null=True, verbose_name='End time')),
                ('reservable', models.BooleanField(default=False, help_text='Allow reservations', verbose_name='Reservable')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_publish_date', to='resources.resource', verbose_name='Resource')),
            ],
        ),
    ]
