# Generated by Django 3.2.23 on 2024-03-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0154_reservation_bulk_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationbulk',
            options={'verbose_name': 'Recurring reservation', 'verbose_name_plural': 'Recurring reservations'},
        ),
        migrations.AlterModelOptions(
            name='reservationreminder',
            options={'verbose_name': 'Reservation reminder', 'verbose_name_plural': 'Reservation reminders'},
        ),
        migrations.AlterField(
            model_name='reservationreminder',
            name='reminder_date',
            field=models.DateTimeField(verbose_name='Reminder date'),
        ),
    ]
