# Generated by Django 3.2.23 on 2024-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0155_reservation_reminder_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='overnight_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Overnight end time'),
        ),
        migrations.AddField(
            model_name='resource',
            name='overnight_reservations',
            field=models.BooleanField(default=False, help_text='Allow overnight reservations for this resource', verbose_name='Overnight reservations'),
        ),
        migrations.AddField(
            model_name='resource',
            name='overnight_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Overnight start time'),
        ),
    ]
