name: Respa CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: [ ubuntu-20.04 ]
    services:
      postgres:
        image: postgis/postgis:14-3.4
        env:
          POSTGRES_USER: respa
          POSTGRES_PASSWORD: respa
          POSTGRES_DB: respa
          DEBUG: true
          SECRET_KEY: respa_secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: [ "3.8", "3.9" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext python-dev libpq-dev gdal-bin -y
          psql -h localhost -U respa -d template1 -c "create extension hstore;"
          psql -h localhost -U respa -d respa -c "create extension hstore;"
        env:
          PGPASSWORD: respa
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Apply migrations
        env:
          DATABASE_URL: postgis://respa:respa@localhost/respa
          DEBUG: true
          SECRET_KEY: respa_secret
        run: |
          python3 manage.py migrate
      - name: Compile translations
        run: |
          python3 manage.py compilemessages --locale en --locale fi --locale sv
      - name: Run tests
        env:
          DATABASE_URL: postgis://respa:respa@localhost/respa
          DEBUG: true
          SECRET_KEY: respa_secret
        run: |
          pytest --cov . --doctest-modules
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1

